### ISSUE TITLE
Invalid parameter "prefix" None None

### ISSUE THREAD

**Issue by mikekaram** [RobotnikAutomation/rb1_base_sim#2]
Hello,

I cloned the repository, along with the rb1_base_common. I _catkin_maked_ my workspace. However,
when I try to run:
`roslaunch -v rb1_base_gazebo rb1_base_gazebo.launch id_robot_a:=robot_a`
It fails with error shown in the title. A screenshot is attached.
 
![rb1_prefix_none_error](https://user-images.githubusercontent.com/23616065/39185807-16043d82-47d1-11e8-97ea-1604198a87bb.png)

Thank you in advance,
Mike

**Comment by alex-arnal** [comment]
Hello,

The robotnik_sensors package that is installed through the apt command is outdated. The latest version of this package can be downloaded from: [robotnik_sensors](https://github.com/RobotnikAutomation/robotnik_sensors). Compiling this version of the package in your workspace should solve the problem.

Alex.

**Comment by mikekaram** [comment]
Oh, thank you very much!
