### ISSUE TITLE
using rosde, still packeges is missing

### ISSUE THREAD

**Issue by atankvadi** [RobotnikAutomation/rb1_base_sim#3]
i am working on Robotnik RB1

I installed packages like **rb1_base _sim, rb1_base_common, robotnik_base_hw**

while i used rosdep, **rosdep install --from-paths /home/robotmania/catkin_ws/src/rb1_base_sim --ignore-src --rosdistro=kinetic -y** it saying that, **#All required rosdeps installed successfully** even after that i can create workspace successfully through catkin_make.

bus still i am unable to launch any file(even I can't see them while i am launching) of them, except rb1_base_pad

so can anyone tell why this is happening and how can i get all required packages.

**Comment by mikekaram** [comment]
Could you provide a type of error or a screenshot of the failing roslaunch?

**Comment by atankvadi** [comment]
here i am attaching the screen shot of error
if I use **roslaunch rb1_base_** and press tab for further directory, it is showing only 2 packages, which you can see in screenshot and if i write manually, also showing the errors
![error](https://user-images.githubusercontent.com/39796468/41348008-a3836f8c-6f0b-11e8-9c26-119e45c3ff56.png)

**Comment by mikekaram** [comment]
Do you source the ROS setup file correctly?
If yes, try to reboot, sometimes it works.

What I am trying to say, is that this type of error has nothing to do with this package, so something is wrong with your ROS setup or environment.

**Comment by atankvadi** [comment]
Thank you for suggestion I got what is the problem
Ros setup file is correctly config 
but now as solution,  every time I have to update my setup.bash, then it will show all required packages.

**Comment by rguzman1** [comment]
In addition, the rb1_base_complete launch is in a different package now:

>roslaunch rb1_base_sim_bringup rb1_base_complete.launch
