### ISSUE TITLE
Elevator joint. How to enable the elevantor joint? 

### ISSUE THREAD

**Issue by ghost** [RobotnikAutomation/rb1_base_sim#6]
Hi, i already set the joint_state_publisher in the rviz to "true" but it dont appear. Is there a way to control the elevator lifting and what is the steps?

**Comment by David-rn** [comment]
Hi, could you give us more information?

For example:
OS: [e.g. Ubuntu 16.04]
Gazebo version: [e.g. Gazebo 9]
ROS version: [e.g. Kinetic]

- Which packages did you install?

- Could you detail the procedure and commands you are running?

**Comment by ghost** [comment]
OS: Ubuntu 16.04
Gazebo version: Gazebo 7
ROS version: Kinetic

    Which packages did you install? rb1_base_sim

    Could you detail the procedure and commands you are running? I just follow the instructions in the github file of rb1_base_sim

**Comment by David-rn** [comment]
Hi,

Have you installed the packages via Ubuntu repositories or have you installed them cloning the repository along with its dependencies? 

I've cloned the repository in a new, void workspace and I had no problem running the command: 
`roslaunch rb1_base_sim_bringup rb1_base_complete.launch`

Could you detail your problem? Posting some photos, if you get any error, etc.
